### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [i-love-coffee-i-love-tea/audogombleed.sh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by i-love-coffee-i-love-tea** [comment]
Thanks for your interest. I put the BSD License header from audogombleed.sh into the file `LICENSE` to make clear it is valid for all files in the project. Please let me know if it meets your requirements.

**Comment by i-love-coffee-i-love-tea** [comment]
May I ask, did you decide against it? I mean it is not really a ZSH plugin, but my intention was actually to make it awesome - i think it really is - and ask awesome list authors to include it. Then you got ahead of me and got me excited. :laughing: 

I wrote tests for nearly everything on the weekend and fixed the last minor bugs, if that matters.

**Comment by unixorn** [comment]
I didn't decide against it - just been busy. It's going into today's update.
